config/routes.rb
Rails.application.routes.draw do
  resources :repos

  root 'repos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  PER_PAGE = 10
  DEFAULT_PAGE = 1
  MAX_TOTAL_ITEMS = 1000

  # GET /repos
  def index
    @search = search_params[:search]
    return @repos if @search.blank?

    page = search_params.fetch(:page, DEFAULT_PAGE).to_i
    result = GithubService.new.search_repos(search: @search, page: page, per_page: PER_PAGE)

    total_count = [result[:total_count], MAX_TOTAL_ITEMS].min
    @repos = WillPaginate::Collection.create(page, PER_PAGE, total_count) do |pager|
      pager.replace(result[:items])
    end
  end

  private

  def search_params
    params.permit(:search, :page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adjust</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repos/_repos.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Url</th>
    <th>Description</th>
  </tr>
  </thead>

  <tbody>
  <% @repos.each do |repo| %>
    <tr>
      <td><%= repo.name %></td>
      <td><%= image_tag repo.owner.avatar_url, size: '16x16' %><%= repo.owner.login %></td>
      <td><%= link_to repo.url, repo.url %></td>
      <td><%= repo.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @repos if @repos %>

app/views/repos/index.html.erb
<h1>Github Repositories</h1>

<%= form_tag(repos_path, method: :get) do %>
  <%= text_field_tag :search, '' %>
  <%= submit_tag 'Search' %>
<% end %>

<h3>Search for: <%= @search %></h3>

<% if @repos %>
  <%= render(partial: 'repos') %>
<% else %>
  <p>Nothing found</p>
<% end %>